###

GET http://localhost:3000/

###
POST http://localhost:3000/users/ 
Content-Type: application/json

{
  "username": "johndoe",
  "name": "John Doe",
  "password": "securepassword123",
  "age": 30,
  "number": "+1234567890"
}
